# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laura Janelle
email: info@laurajanelle.com
description: High fashion craft jewelry wholesaler.
url: https://acmotanya.github.io/cousin-op
baseurl: "/cousin-op" # the subpath of your site, e.g. /blog
twitter_username: LauraJanelleCo

# Footer settings
footer: Laura Janelle

# Build settings
markdown: kramdown
permalink: pretty
